CREATE TABLE gateway (
  SERIAL_NUMBER VARCHAR(250) PRIMARY KEY,
  HUMAN_NAME VARCHAR(250) NOT NULL,
  IPV4 VARCHAR(250) NOT NULL
);

CREATE TABLE device (
  UID INT PRIMARY KEY,
  vendor VARCHAR(250) ,
  DATE_CREATED VARCHAR(250) ,
  status VARCHAR(250) ,
  SERIAL_NUMBER VARCHAR(250) REFERENCES gateway(SERIAL_NUMBER)
);